#!/bin/bash
export HOME=/home/ubuntu
PATH=/home/ubuntu/.rvm/gems/jruby-1.7.11/bin:/home/ubuntu/.rvm/gems/jruby-1.7.11@global/bin:/home/ubuntu/.rvm/rubies/jruby-1.7.11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin
cd /home/ubuntu/
exec setuidgid ubuntu /usr/bin/python /home/ubuntu/applications/apache-storm-0.9.2-incubating/bin/storm supervisor > /home/ubuntu/data/storm/logs/storm-supervisor.log 2>&1
